In [47]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [48]:
import numpy as np
import pandas as pd
df = pd.read_csv('rainfall.csv')
from sklearn.preprocessing import LabelEncoder
Label = LabelEncoder()
df['rainfall'] = Label.fit_transform(df['rainfall'])

In [49]:
df.rename(str.strip, axis = 1, inplace = True)

In [50]:
df = df.drop(160)

In [55]:
x = df.drop(['rainfall'], axis = 1)
y = df['rainfall']

In [69]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 23)
from sklearn.linear_model import LogisticRegression
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# x_train = pd.DataFrame(scaler.fit_transform(x_train))
# x_test = pd.DataFrame(scaler.transform(x_test))
model = LogisticRegression()
model.fit(x_train, y_train)

C:\Users\admin\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [79]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix 
def Metrics(model, x, y):
    y_pred = model.predict(x)
    ac_sc = accuracy_score(y, y_pred)
    print(ac_sc)

    pr_sc = precision_score(y, y_pred)
    print(pr_sc)

    c = confusion_matrix(y, y_pred)
    print(c)


Metrics(model, x_train, y_train)

0.821917808219178
0.8516746411483254
[[ 62  31]
 [ 21 178]]


In [81]:
Metrics(model, x_test, y_test)

0.7945205479452054
0.8541666666666666
[[17  7]
 [ 8 41]]


In [97]:
y_pred = model.predict(x)
y_pred

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0,

In [99]:
y_probs = model.predict_proba(x_train)[:, 1]
y_probs

array([9.16578466e-01, 5.27076662e-01, 9.63808215e-01, 8.81023030e-01,
       4.68068199e-01, 8.90045700e-02, 8.95393589e-01, 7.19505480e-01,
       7.94991020e-01, 8.01026090e-01, 5.54518800e-01, 2.72960662e-02,
       9.74617464e-01, 9.67057726e-01, 8.73232017e-01, 9.03761535e-01,
       6.47075871e-01, 8.01465281e-01, 9.33078257e-01, 8.50883268e-01,
       8.77599412e-01, 8.96003530e-01, 4.43550865e-01, 7.23619696e-01,
       9.82575243e-01, 9.81495235e-01, 7.96909643e-01, 4.01652228e-01,
       7.51451938e-01, 9.08594547e-01, 8.79690970e-01, 1.32360720e-01,
       9.23496088e-01, 3.50174411e-02, 8.38822260e-01, 9.78719707e-01,
       7.14683461e-01, 5.51432876e-01, 7.53150748e-01, 9.67273669e-01,
       5.77334780e-01, 9.56753161e-01, 5.76730607e-01, 2.81588786e-01,
       9.85705379e-01, 7.98318017e-01, 9.32878015e-01, 9.64067504e-01,
       1.91096681e-01, 8.17413840e-01, 9.85476920e-01, 7.16632469e-01,
       9.70212146e-01, 4.81708144e-01, 3.71278906e-01, 5.35427904e-01,
      