In [3]:
import numpy as np
n = np.array([1, 2, 3, 4])
print(n)

[1 2 3 4]


In [3]:
import numpy as np


In [6]:

min_val = np.array([[4, 5, 7],
                   [5, 6, 1],
                   [8, 3, 1]])
min_val

array([[4, 5, 7],
       [5, 6, 1],
       [8, 3, 1]])

In [8]:
np.apply_along_axis(lambda x : np.min(x), arr = min_val, axis = 0)

array([4, 3, 1])

In [10]:
np.apply_along_axis(lambda x : np.min(x), arr = min_val, axis = 1)

array([4, 1, 1])

In [12]:
np.apply_along_axis(lambda x : np.min(x), arr = min_val)

TypeError: apply_along_axis() missing 1 required positional argument: 'axis'

In [16]:
array_2d = np.array([[1, 2, 3],
                     [10, 5, 6],
                     [7, 8, 9]])
np.mean(array_2d)
np.median(array_2d)

6.0

In [19]:
import pandas as pd
pd.Series([sum, print, len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object