In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import PolynomialFeatures

In [19]:
data = fetch_california_housing()

In [21]:
data

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [25]:
print(data.feature_names)
print(data.target)
features = data.feature_names
target = data.target

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
[4.526 3.585 3.521 ... 0.923 0.847 0.894]


In [27]:
interaction =  PolynomialFeatures(
degree = 3, include_bias = False, interaction_only = True)
features_interaction = interaction.fit_transform(features)

ValueError: Expected 2D array, got 1D array instead:
array=['MedInc' 'HouseAge' 'AveRooms' 'AveBedrms' 'Population' 'AveOccup'
 'Latitude' 'Longitude'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [37]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import fetch_california_housing
import numpy as np

# Load dataset (replace this with your own dataset if necessary)
data = fetch_california_housing()
features = data.data  # This should be the actual data (2D array)
target = data.target

# Initialize PolynomialFeatures
interaction = PolynomialFeatures(degree=3, include_bias=False, interaction_only=True)

# Fit and transform the features (ensure it's 2D)
features_interaction = interaction.fit_transform(features)

# Check the transformed features
print(features_interaction)

[[ 8.32520000e+00  4.10000000e+01  6.98412698e+00 ... -1.00581709e+05
  -1.49088331e+06 -1.18324072e+04]
 [ 8.30140000e+00  2.10000000e+01  6.23813708e+00 ... -6.19133549e+05
  -1.11100253e+07 -9.76276391e+03]
 [ 7.25740000e+00  5.20000000e+01  8.28813559e+00 ... -1.69903931e+05
  -2.29488486e+06 -1.29654512e+04]
 ...
 [ 1.70000000e+00  1.70000000e+01  5.20554273e+00 ... -2.83886882e+05
  -4.81316253e+06 -1.11158488e+04]
 [ 1.86720000e+00  1.80000000e+01  5.32951289e+00 ... -1.90872513e+05
  -3.54468287e+06 -1.01566844e+04]
 [ 2.38860000e+00  1.60000000e+01  5.25471698e+00 ... -4.40071233e+05
  -6.62045448e+06 -1.24914235e+04]]


In [31]:
features.shape

(20640, 8)

In [39]:
from sklearn.linear_model import LinearRegression
regression =  LinearRegression()
model = regression.fit(features_interaction, target)

In [41]:
model

LinearRegression()

In [43]:
features[0]

array([   8.3252    ,   41.        ,    6.98412698,    1.02380952,
        322.        ,    2.55555556,   37.88      , -122.23      ])

In [45]:
features_interaction[0]

array([ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,  1.02380952e+00,
        3.22000000e+02,  2.55555556e+00,  3.78800000e+01, -1.22230000e+02,
        3.41333200e+02,  5.81442540e+01,  8.52341905e+00,  2.68071440e+03,
        2.12755111e+01,  3.15358576e+02, -1.01758920e+03,  2.86349206e+02,
        4.19761905e+01,  1.32020000e+04,  1.04777778e+02,  1.55308000e+03,
       -5.01143000e+03,  7.15041572e+00,  2.24888889e+03,  1.78483245e+01,
        2.64558730e+02, -8.53669841e+02,  3.29666667e+02,  2.61640212e+00,
        3.87819048e+01, -1.25140238e+02,  8.22888889e+02,  1.21973600e+04,
       -3.93580600e+04,  9.68044444e+01, -3.12365556e+02, -4.63007240e+03,
        2.38391441e+03,  3.49460181e+02,  1.09909290e+05,  8.72295956e+02,
        1.29297016e+04, -4.17211570e+04,  5.95286410e+01,  1.87224498e+04,
        1.48590871e+02,  2.20250434e+03, -7.10697216e+03,  2.74454093e+03,
        2.17820709e+01,  3.22867114e+02, -1.04181751e+03,  6.85071458e+03,
        1.01545461e+05, -

In [47]:
import numpy as np

In [49]:
interaction_term = np.multiply(features[:, 0], features[:, 1])

In [51]:
interaction_term[0]

341.33320000000003

In [53]:
from sklearn.linear_model import Ridge